# Obtain Training and Testing Set from Training Data

In [1]:
import os
import pandas as pd

In [2]:
# These were randomly selected
file = os.path.join("data", "test_samples.csv")
test_samples = pd.read_csv(file)
test_samples.head()

    cell_code            moa
0  P3WKxyuXrF  DNAMetabolism
1  PynJEZPI7T  DNAMetabolism
2  MYRxbkGeq6  DNAMetabolism
3  erGVwRyWun  DNAMetabolism
4  xmhDruiMi7  DNAMetabolism

In [3]:
file = os.path.join("data", "training_data.csv")
df = pd.read_csv(file)

print(df.shape)
df.head()

(51267, 123)

,cell_code,cell_id,plate,replicate,well,field,actin.s.area,actin.s.perimeter,actin.s.radius.mean,actin.s.radius.sd,...,DNA.h.ent.s3,DNA.h.dva.s3,DNA.h.den.s3,DNA.h.f12.s3,DNA.h.f13.s3,dist.10.nn,dist.20.nn,dist.30.nn,nuclear.displacement,target
0,OaJHcDs2kh,1,P1,1,C10,1,579,90,13.942759,4.352958,...,0.0,0.0,0.0,0.0,0.0,128.889522,178.595764,207.187370,5.938882,adrenoceptor
1,nwLFF4l070,2,P1,1,C10,1,1132,136,20.179007,4.583255,...,0.0,0.0,0.0,0.0,0.0,79.885304,123.697473,190.598760,0.478024,adrenoceptor
2,JU4SIplWZ7,3,P1,1,C10,1,736,99,15.209404,2.408709,...,0.0,0.0,0.0,0.0,0.0,64.370636,88.931673,127.452918,3.928325,adrenoceptor
3,pqkTwaHa2L,4,P1,1,C10,1,611,92,14.398528,3.662234,...,0.0,0.0,0.0,0.0,0.0,87.536494,121.879169,160.752674,3.336081,adrenoceptor
4,pB2BlQoW94,5,P1,1,C10,1,585,93,14.030675,3.408844,...,0.0,0.0,0.0,0.0,0.0,105.866735,142.023858,182.990012,2.343776,adrenoceptor

## Split Off True Test Set and True Training Set

In [4]:
train_df = df.query("cell_code not in @test_samples.cell_code")
test_df = df.query("cell_code in @test_samples.cell_code")

In [5]:
assert len(set(train_df.cell_code).intersection(set(test_df.cell_code))) == 0

In [6]:
file = os.path.join("data", "train_ebfeatures.csv")
train_df.to_csv(file, sep=',', index=False)

In [7]:
file = os.path.join("data", "test_ebfeatures.csv")
test_df.to_csv(file, sep=',', index=False)